networks:
  common-network:
    driver: bridge

volumes:
  postgres_data:

services:
  postgres:
    image: postgres:18-alpine
    restart: on-failure
    container_name: postgres-all-on-sport
    networks:
      - common-network
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5

# Пока не используем, нужно дописать саму аппку
#  app:
#    image: all-on-sport
#    container_name: app-all-on-sport
#    build:
#      context: .
#      args:
#        DOCKER_BUILDKIT: 1
#    restart: "no"
#    ports:
#      - "4444:4444"
#    environment:
#      SPRING_LIQUIBASE_URL: jdbc:postgresql://postgres:5432/all-on-sport?useSSL=false&allowPublicKeyRetrieval=true&autoReconnect=true?createDatabaseIfNotExist=true
#      SPRING_LIQUIBASE_USER: postgres
#      SPRING_LIQUIBASE_PASSWORD: postgres
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/all-on-sport?useSSL=false&allowPublicKeyRetrieval=true&autoReconnect=true?createDatabaseIfNotExist=true
#      SPRING_DATASOURCE_USERNAME: postgres
#      SPRING_DATASOURCE_PASSWORD: postgres
#      SPRING_LIQUIBASE_CHANGELOG: classpath:/database/db.changelog.yml
